### ISSUE TITLE
No nonRiemannsolver for compressible flow in Eulerian SPH scheme.

### ISSUE THREAD

**Issue by Bo-Zhang1995** [Xiangyu-Hu/SPHinXsys#335] opened 2023-06-13 07:52 UTC
Currently, it seems that only the HLLC Riemann solver with and without a limiter for the compressible flow is in the Eulerian SPH scheme.
It should include a non-Riemann solver as well for better testing of more cases.

**Comment by Xiangyu-Hu** [comment] 2023-06-13 10:01
@ZhentongWang please consider this issue.

**Comment by ZhentongWang** [comment] 2023-06-13 10:24
Sure, I will add the non-Riemann solver for compressible framework soon.

**Comment by Xiangyu-Hu** [comment] 2023-06-13 12:37
@ZhentongWang I have created a branch for this issue. Please work on this branch directly.

**Comment by Xiangyu-Hu** [comment] 2023-06-13 16:14
the issue is close due to the merged pull request #337

**Closed by Xiangyu-Hu** 2023-06-13 16:14 UTC
